In [1]:
from netCDF4 import Dataset
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
#import cartopy.crs as ccrs
import pandas as pd

import time

In [3]:
# - grid file
gridfile = '/store/CT1/hmg2840/lbrodeau/eNATL60/eNATL60-I/coordinates_eNATL60.nc'
gridfile_ORCA1 = '/scratch/cnt0024/hmg2840/albert7a/eORCA1/eORCA1-I/IPSLCM6ALR_eORCA1.2_mesh_mask.nc'

# - Define read data function
def read_datagrid(gridfile,latmin=None,latmax=None,lonmin=None,lonmax=None):
    """Return navlon,navlat."""
    ncfile = Dataset(gridfile,'r')
    # load navlon and navlat
    _navlon = ncfile.variables['glamt'][:,:]
    _navlat = ncfile.variables['gphit'][:,:]
    #-Define domain
    domain = (lonmin<_navlon) * (_navlon<lonmax) * (latmin<_navlat) * (_navlat<latmax)
    where = np.where(domain)
    vlats = _navlat[where]
    vlons = _navlon[where]
    #get indice
    jmin = where[0][vlats.argmin()]
    jmax = where[0][vlats.argmax()]
    imin = where[1][vlons.argmin()]
    imax = where[1][vlons.argmax()]
    #load arrays
    navlon = _navlon[jmin:jmax+1,imin:imax+1]
    navlat = _navlat[jmin:jmax+1,imin:imax+1]
    return navlon,navlat,jmin,jmax,imin,imax

def read_datagrid_ORCA1(gridfile,latmin=None,latmax=None,lonmin=None,lonmax=None):
    """Return navlon,navlat."""
    ncfile = Dataset(gridfile,'r')
    # load navlon and navlat
    _navlon = ncfile.variables['nav_lon'][:,:]
    _navlat = ncfile.variables['nav_lat'][:,:]
    #-Define domain
    domain = (lonmin<_navlon) * (_navlon<lonmax) * (latmin<_navlat) * (_navlat<latmax)
    where = np.where(domain)
    vlats = _navlat[where]
    vlons = _navlon[where]
    #get indice
    jmin_ORCA = where[0][vlats.argmin()]
    jmax_ORCA = where[0][vlats.argmax()]
    imin_ORCA = where[1][vlons.argmin()]
    imax_ORCA = where[1][vlons.argmax()]
    #load arrays
    navlon_ORCA = _navlon[jmin_ORCA:jmax_ORCA+1,imin_ORCA:imax_ORCA+1]
    navlat_ORCA = _navlat[jmin_ORCA:jmax_ORCA+1,imin_ORCA:imax_ORCA+1]
    return navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA

In [4]:
y1 = 55. 
y2 = 62.
x1 = -49.
x2 = -56.

navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA = read_datagrid_ORCA1(gridfile_ORCA1,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

In [6]:
navlon_ORCA.shape

(13, 8)

In [8]:
print(len(navlon_ORCA.flatten()))

104

In [ ]:
for i in range(len(navlon_ORCA.flatten())):
    print(navlon_ORCA.flatten()[i],navlat_ORCA.flatten()[i])

In [15]:
np.shape(navlon_ORCA)[1]

8

In [17]:
list_i = []
list_j = []
list_name = []
list_lat = []
list_lon = []

ii = 0
jj = 0

for i in range(len(navlon_ORCA.flatten())):
    list_i.append(imin_ORCA+ii)
    list_j.append(jmin_ORCA+jj)
    list_lat.append(navlat_ORCA[jj,ii])
    list_lon.append(navlon_ORCA[jj,ii])
    list_name.append('Box_'+str(i))
    ii = ii + 1
    if ii > np.shape(navlon_ORCA)[1]-1:
        ii = 0
        jj = jj + 1

In [19]:
for i in range(len(navlon_ORCA.flatten())):
    print(navlon_ORCA.flatten()[i],list_lon[i],navlat_ORCA.flatten()[i],list_lat[i])

-55.25955 -55.25955 54.724823 54.724823
-54.227295 -54.227295 54.807053 54.807053
-53.191807 -53.191807 54.887318 54.887318
-52.153095 -52.153095 54.9655 54.9655
-51.111195 -51.111195 55.041496 55.041496
-50.066128 -50.066128 55.115192 55.115192
-49.017937 -49.017937 55.18649 55.18649
-47.96667 -47.96667 55.25528 55.25528
-55.40519 -55.40519 55.30585 55.30585
-54.37062 -54.37062 55.39171 55.39171
-53.33254 -53.33254 55.475517 55.475517
-52.290966 -52.290966 55.557167 55.557167
-51.245926 -51.245926 55.636543 55.636543
-50.197456 -50.197456 55.713535 55.713535
-49.14559 -49.14559 55.78803 55.78803
-48.09039 -48.09039 55.859924 55.859924
-55.559578 -55.559578 55.880455 55.880455
-54.522594 -54.522594 55.96999 55.96999
-53.481815 -53.481815 56.057404 56.057404
-52.437252 -52.437252 56.142574 56.142574
-51.38893 -51.38893 56.225388 56.225388
-50.336895 -50.336895 56.30573 56.30573
-49.28118 -49.28118 56.38348 56.38348
-48.22184 -48.22184 56.458534 56.458534
-55.7231 -55.7231 56.448734 56.448734
-54.683613 -54.683613 56.542 56.542
-53.64002 -53.64002 56.63307 56.63307
-52.59234 -52.59234 56.721825 56.721825
-51.540596 -51.540596 56.808132 56.808132
-50.484825 -50.484825 56.89188 56.89188
-49.42508 -49.42508 56.972942 56.972942
-48.361404 -48.361404 57.051212 57.051212
-55.896152 -55.896152 57.010788 57.010788
-54.854073 -54.854073 57.10784 57.10784
-53.80756 -53.80756 57.20263 57.20263
-52.756634 -52.756634 57.295013 57.295013
-51.70132 -51.70132 57.384876 57.384876
-50.641655 -50.641655 57.472084 57.472084
-49.57769 -49.57769 57.556522 57.556522
-48.50948 -48.50948 57.63807 57.63807
-56.079166 -56.079166 57.566715 57.566715
-55.034405 -55.034405 57.66761 57.66761
-53.984867 -53.984867 57.766167 57.766167
-52.930565 -52.930565 57.862247 57.862247
-51.871532 -51.871532 57.955715 57.955715
-50.807808 -50.807808 58.04645 58.04645
-49.739437 -49.739437 58.13432 58.13432
-48.66648 -48.66648 58.2192 58.2192
-56.272587 -56.272587 58.116604 58.116604
-55.225056 -55.225056 58.2214 58.2214
-54.172386 -54.172386 58.323784 58.323784
-53.114586 -53.114586 58.42361 58.42361
-52.05169 -52.05169 58.520752 58.520752
-50.98373 -50.98373 58.61507 58.61507
-49.910767 -49.910767 58.706432 58.706432
-48.832855 -48.832855 58.794712 58.794712
-56.47688 -56.47688 58.66054 58.66054
-55.426502 -55.426502 58.769295 58.769295
-54.37059 -54.37059 58.875565 58.875565
-53.309166 -53.309166 58.979202 58.979202
-52.24226 -52.24226 59.080074 59.080074
-51.169903 -51.169903 59.178036 59.178036
-50.092155 -50.092155 59.272953 59.272953
-49.009075 -49.009075 59.364693 59.364693
-56.69254 -56.69254 59.198616 59.198616
-55.639233 -55.639233 59.311382 59.311382
-54.579987 -54.579987 59.421597 59.421597
-53.514816 -53.514816 59.529106 59.529106
-52.44375 -52.44375 59.63377 59.63377
-51.36683 -51.36683 59.73544 59.73544
-50.2841 -50.2841 59.833977 59.833977
-49.195637 -49.195637 59.92924 59.92924
-56.920086 -56.920086 59.7309 59.7309
-55.863777 -55.863777 59.84774 59.84774
-54.801098 -54.801098 59.96196 59.96196
-53.732063 -53.732063 60.073402 60.073402
-52.656696 -52.656696 60.181923 60.181923
-51.57504 -51.57504 60.287365 60.287365
-50.48714 -50.48714 60.389587 60.389587
-49.393074 -49.393074 60.488445 60.488445
-57.160065 -57.160065 60.257465 60.257465
-56.100685 -56.100685 60.378437 60.378437
-55.034485 -55.034485 60.496723 60.496723
-53.961468 -53.961468 60.612167 60.612167
-52.88166 -52.88166 60.724606 60.724606
-51.7951 -51.7951 60.833893 60.833893
-50.70184 -50.70184 60.93987 60.93987
-49.60195 -49.60195 61.04239 61.04239
-57.41305 -57.41305 60.778378 60.778378
-56.350544 -56.350544 60.903545 60.903545
-55.280735 -55.280735 61.025963 61.025963
-54.20363 -54.20363 61.145466 61.145466
-53.11924 -53.11924 61.261898 61.261898
-52.027615 -52.027615 61.37509 61.37509
-50.9288 -50.9288 61.484898 61.484898
-49.822865 -49.822865 61.591152 61.591152
-57.679653 -57.679653 61.29369 61.29369
-56.613968 -56.613968 61.423115 61.423115
-55.540474 -55.540474 61.549732 61.549732
-54.459167 -54.459167 61.673367 61.673367
-53.37007 -53.37007 61.793858 61.793858
-52.273216 -52.273216 61.911034 61.911034
-51.16865 -51.16865 62.02474 62.02474
-50.056454 -50.056454 62.134804 62.134804

In [21]:
ncfile = Dataset(gridfile_ORCA1,'r')
# load navlon and navlat
_navlon = ncfile.variables['nav_lon'][:,:]
_navlat = ncfile.variables['nav_lat'][:,:]

list_lat_eORCA1 = []
list_lon_eORCA1 = []
ii = 0
jj = 0

for i in range(len(navlon_ORCA.flatten())):
    list_lat_eORCA1.append(_navlat[jmin_ORCA+jj,imin_ORCA+ii])
    list_lon_eORCA1.append(_navlon[jmin_ORCA+jj,imin_ORCA+ii])
    ii = ii + 1
    if ii > np.shape(navlon_ORCA)[1]-1:
        ii = 0
        jj = jj + 1

In [22]:
for i in range(len(navlon_ORCA.flatten())):
    print(list_lon[i],list_lon_eORCA1[i],list_lat[i],list_lat_eORCA1[i])

-55.25955 -55.25955 54.724823 54.724823
-54.227295 -54.227295 54.807053 54.807053
-53.191807 -53.191807 54.887318 54.887318
-52.153095 -52.153095 54.9655 54.9655
-51.111195 -51.111195 55.041496 55.041496
-50.066128 -50.066128 55.115192 55.115192
-49.017937 -49.017937 55.18649 55.18649
-47.96667 -47.96667 55.25528 55.25528
-55.40519 -55.40519 55.30585 55.30585
-54.37062 -54.37062 55.39171 55.39171
-53.33254 -53.33254 55.475517 55.475517
-52.290966 -52.290966 55.557167 55.557167
-51.245926 -51.245926 55.636543 55.636543
-50.197456 -50.197456 55.713535 55.713535
-49.14559 -49.14559 55.78803 55.78803
-48.09039 -48.09039 55.859924 55.859924
-55.559578 -55.559578 55.880455 55.880455
-54.522594 -54.522594 55.96999 55.96999
-53.481815 -53.481815 56.057404 56.057404
-52.437252 -52.437252 56.142574 56.142574
-51.38893 -51.38893 56.225388 56.225388
-50.336895 -50.336895 56.30573 56.30573
-49.28118 -49.28118 56.38348 56.38348
-48.22184 -48.22184 56.458534 56.458534
-55.7231 -55.7231 56.448734 56.448734
-54.683613 -54.683613 56.542 56.542
-53.64002 -53.64002 56.63307 56.63307
-52.59234 -52.59234 56.721825 56.721825
-51.540596 -51.540596 56.808132 56.808132
-50.484825 -50.484825 56.89188 56.89188
-49.42508 -49.42508 56.972942 56.972942
-48.361404 -48.361404 57.051212 57.051212
-55.896152 -55.896152 57.010788 57.010788
-54.854073 -54.854073 57.10784 57.10784
-53.80756 -53.80756 57.20263 57.20263
-52.756634 -52.756634 57.295013 57.295013
-51.70132 -51.70132 57.384876 57.384876
-50.641655 -50.641655 57.472084 57.472084
-49.57769 -49.57769 57.556522 57.556522
-48.50948 -48.50948 57.63807 57.63807
-56.079166 -56.079166 57.566715 57.566715
-55.034405 -55.034405 57.66761 57.66761
-53.984867 -53.984867 57.766167 57.766167
-52.930565 -52.930565 57.862247 57.862247
-51.871532 -51.871532 57.955715 57.955715
-50.807808 -50.807808 58.04645 58.04645
-49.739437 -49.739437 58.13432 58.13432
-48.66648 -48.66648 58.2192 58.2192
-56.272587 -56.272587 58.116604 58.116604
-55.225056 -55.225056 58.2214 58.2214
-54.172386 -54.172386 58.323784 58.323784
-53.114586 -53.114586 58.42361 58.42361
-52.05169 -52.05169 58.520752 58.520752
-50.98373 -50.98373 58.61507 58.61507
-49.910767 -49.910767 58.706432 58.706432
-48.832855 -48.832855 58.794712 58.794712
-56.47688 -56.47688 58.66054 58.66054
-55.426502 -55.426502 58.769295 58.769295
-54.37059 -54.37059 58.875565 58.875565
-53.309166 -53.309166 58.979202 58.979202
-52.24226 -52.24226 59.080074 59.080074
-51.169903 -51.169903 59.178036 59.178036
-50.092155 -50.092155 59.272953 59.272953
-49.009075 -49.009075 59.364693 59.364693
-56.69254 -56.69254 59.198616 59.198616
-55.639233 -55.639233 59.311382 59.311382
-54.579987 -54.579987 59.421597 59.421597
-53.514816 -53.514816 59.529106 59.529106
-52.44375 -52.44375 59.63377 59.63377
-51.36683 -51.36683 59.73544 59.73544
-50.2841 -50.2841 59.833977 59.833977
-49.195637 -49.195637 59.92924 59.92924
-56.920086 -56.920086 59.7309 59.7309
-55.863777 -55.863777 59.84774 59.84774
-54.801098 -54.801098 59.96196 59.96196
-53.732063 -53.732063 60.073402 60.073402
-52.656696 -52.656696 60.181923 60.181923
-51.57504 -51.57504 60.287365 60.287365
-50.48714 -50.48714 60.389587 60.389587
-49.393074 -49.393074 60.488445 60.488445
-57.160065 -57.160065 60.257465 60.257465
-56.100685 -56.100685 60.378437 60.378437
-55.034485 -55.034485 60.496723 60.496723
-53.961468 -53.961468 60.612167 60.612167
-52.88166 -52.88166 60.724606 60.724606
-51.7951 -51.7951 60.833893 60.833893
-50.70184 -50.70184 60.93987 60.93987
-49.60195 -49.60195 61.04239 61.04239
-57.41305 -57.41305 60.778378 60.778378
-56.350544 -56.350544 60.903545 60.903545
-55.280735 -55.280735 61.025963 61.025963
-54.20363 -54.20363 61.145466 61.145466
-53.11924 -53.11924 61.261898 61.261898
-52.027615 -52.027615 61.37509 61.37509
-50.9288 -50.9288 61.484898 61.484898
-49.822865 -49.822865 61.591152 61.591152
-57.679653 -57.679653 61.29369 61.29369
-56.613968 -56.613968 61.423115 61.423115
-55.540474 -55.540474 61.549732 61.549732
-54.459167 -54.459167 61.673367 61.673367
-53.37007 -53.37007 61.793858 61.793858
-52.273216 -52.273216 61.911034 61.911034
-51.16865 -51.16865 62.02474 62.02474
-50.056454 -50.056454 62.134804 62.134804

In [46]:
panda_box=pd.DataFrame({'i' : list_i, 'j' : list_j, 'lat' : list_lat, 'lon' : list_lon, 'lat_eORCA1' : list_lat_eORCA1, 'lon_eORCA1' : list_lon_eORCA1},index = list_name)
panda_box.to_csv('boxes_LS_1x1_eORCA1_mine.csv',sep = '\t')

In [5]:


# - Define box dimensions
a = (np.shape(navlon_ORCA)[0]-2.)*(np.shape(navlat_ORCA)[1]-2.)
Box_arr = np.empty((int(a),6),dtype=np.dtype('U100'))
print(a)

ii = 0
jj = 0
for i in np.arange(0,int(a),1):
    delta_lat1 = np.abs(navlat_ORCA[ii+1,jj] - navlat_ORCA[ii,jj])/2.
    delta_lat2 = np.abs(navlat_ORCA[ii+2,jj] - navlat_ORCA[ii+1,jj])/2.
    delta_lon1 = np.abs(navlon_ORCA[ii,jj+1] - navlon_ORCA[ii,jj])/2.
    delta_lon2 = np.abs(navlon_ORCA[ii,jj+2] - navlon_ORCA[ii,jj+1])/2.    
    Box_arr[i,:] = [str(navlat_ORCA[ii,jj]+delta_lat1),str(navlat_ORCA[ii+1,jj]+delta_lat2),str(navlon_ORCA[ii,jj]+delta_lon1),str(navlon_ORCA[ii,jj+1]+delta_lon2),'Box_'+str(i),str(i)]
    ii = ii + 1
    if ii >= int(np.shape(navlon_ORCA)[0])-2:
        ii = 0
        jj = jj + 1

name = Box_arr[:,4]

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

for i in np.arange(0,int(a),1):
    
    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
    box_name = Box_arr[i,4]
    print(box_name)
    
    # - Obtain navlon and Navlat
    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
    list_imin.append(imin)
    list_imax.append(imax)
    list_jmin.append(jmin)
    list_jmax.append(jmax)
    list_name.append(box_name)
    list_latmin.append(y1)
    list_latmax.append(y2)
    list_lonmin.append(x1)
    list_lonmax.append(x2)
    
panda_box=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax },index = list_name)
panda_box.to_csv('boxes_LS_1x1_eNATL60.csv',sep = '\t')

66.0
Box_0
Box_1
Box_2
Box_3
Box_4
Box_5
Box_6
Box_7
Box_8
Box_9
Box_10
Box_11
Box_12
Box_13
Box_14
Box_15
Box_16
Box_17
Box_18
Box_19
Box_20
Box_21
Box_22
Box_23
Box_24
Box_25
Box_26
Box_27
Box_28
Box_29
Box_30
Box_31
Box_32
Box_33
Box_34
Box_35
Box_36
Box_37
Box_38
Box_39
Box_40
Box_41
Box_42
Box_43
Box_44
Box_45
Box_46
Box_47
Box_48
Box_49
Box_50
Box_51
Box_52
Box_53
Box_54
Box_55
Box_56
Box_57
Box_58
Box_59
Box_60
Box_61
Box_62
Box_63
Box_64
Box_65

In [7]:
#Define region
y1 = 32.5 
y2 = 41.5
x1 = -59.
x2 = -71.6

navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA = read_datagrid_ORCA1(gridfile_ORCA1,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

# - Define box dimensions
a = (np.shape(navlon_ORCA)[0]-2.)*(np.shape(navlat_ORCA)[1]-2.)
Box_arr = np.empty((int(a),6),dtype=np.dtype('U100'))
print(a)

ii = 0
jj = 0
for i in np.arange(0,int(a),1):
    delta_lat1 = np.abs(navlat_ORCA[ii+1,jj] - navlat_ORCA[ii,jj])/2.
    delta_lat2 = np.abs(navlat_ORCA[ii+2,jj] - navlat_ORCA[ii+1,jj])/2.
    delta_lon1 = np.abs(navlon_ORCA[ii,jj+1] - navlon_ORCA[ii,jj])/2.
    delta_lon2 = np.abs(navlon_ORCA[ii,jj+2] - navlon_ORCA[ii,jj+1])/2.    
    Box_arr[i,:] = [str(navlat_ORCA[ii,jj]+delta_lat1),str(navlat_ORCA[ii+1,jj]+delta_lat2),str(navlon_ORCA[ii,jj]+delta_lon1),str(navlon_ORCA[ii,jj+1]+delta_lon2),'Box_'+str(i),str(i)]
    ii = ii + 1
    if ii >= int(np.shape(navlon_ORCA)[0])-2:
        ii = 0
        jj = jj + 1

name = Box_arr[:,4]


list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

for i in np.arange(0,int(a),1):

    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
    box_name = Box_arr[i,4]
    print(box_name)
    
    # - Obtain navlon and Navlat
    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

    list_imin.append(imin)
    list_imax.append(imax)
    list_jmin.append(jmin)
    list_jmax.append(jmax)
    list_name.append(box_name)
    list_latmin.append(y1)
    list_latmax.append(y2)
    list_lonmin.append(x1)
    list_lonmax.append(x2)
    
panda_box_GS=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_GS.to_csv('boxes_GS_1x1_eNATL60.csv',sep = '\t')

110.0
Box_0
Box_1
Box_2
Box_3
Box_4
Box_5
Box_6
Box_7
Box_8
Box_9
Box_10
Box_11
Box_12
Box_13
Box_14
Box_15
Box_16
Box_17
Box_18
Box_19
Box_20
Box_21
Box_22
Box_23
Box_24
Box_25
Box_26
Box_27
Box_28
Box_29
Box_30
Box_31
Box_32
Box_33
Box_34
Box_35
Box_36
Box_37
Box_38
Box_39
Box_40
Box_41
Box_42
Box_43
Box_44
Box_45
Box_46
Box_47
Box_48
Box_49
Box_50
Box_51
Box_52
Box_53
Box_54
Box_55
Box_56
Box_57
Box_58
Box_59
Box_60
Box_61
Box_62
Box_63
Box_64
Box_65
Box_66
Box_67
Box_68
Box_69
Box_70
Box_71
Box_72
Box_73
Box_74
Box_75
Box_76
Box_77
Box_78
Box_79
Box_80
Box_81
Box_82
Box_83
Box_84
Box_85
Box_86
Box_87
Box_88
Box_89
Box_90
Box_91
Box_92
Box_93
Box_94
Box_95
Box_96
Box_97
Box_98
Box_99
Box_100
Box_101
Box_102
Box_103
Box_104
Box_105
Box_106
Box_107
Box_108
Box_109

In [ ]:
y1 = 41. 
y2 = 56.
x1 = -19.
x2 = -41.

navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA = read_datagrid_ORCA1(gridfile_ORCA1,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

# - Define box dimensions
a = (np.shape(navlon_ORCA)[0]-2.)*(np.shape(navlat_ORCA)[1]-2.)
Box_arr = np.empty((int(a),6),dtype=np.dtype('U100'))
print(a)

ii = 0
jj = 0
for i in np.arange(0,int(a),1):
    delta_lat1 = np.abs(navlat_ORCA[ii+1,jj] - navlat_ORCA[ii,jj])/2.
    delta_lat2 = np.abs(navlat_ORCA[ii+2,jj] - navlat_ORCA[ii+1,jj])/2.
    delta_lon1 = np.abs(navlon_ORCA[ii,jj+1] - navlon_ORCA[ii,jj])/2.
    delta_lon2 = np.abs(navlon_ORCA[ii,jj+2] - navlon_ORCA[ii,jj+1])/2.        
    Box_arr[i,:] = [str(navlat_ORCA[ii,jj]+delta_lat1),str(navlat_ORCA[ii+1,jj]+delta_lat2),str(navlon_ORCA[ii,jj]+delta_lon1),str(navlon_ORCA[ii,jj+1]+delta_lon2),'Box_'+str(i),str(i)]
    ii = ii + 1
    if ii >= int(np.shape(navlon_ORCA)[0])-2:
        ii = 0
        jj = jj + 1
        
name = Box_arr[:,4]

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

i=0

y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
box_name = Box_arr[i,4]
print(box_name)
    
# - Obtain navlon and Navlat
navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
list_imin.append(imin)
list_imax.append(imax)
list_jmin.append(jmin)
list_jmax.append(jmax)
list_name.append(box_name)
list_latmin.append(y1)
list_latmax.append(y2)
list_lonmin.append(x1)
list_lonmax.append(x2)

panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_MNA.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

for i in np.arange(1,200,1):
    
    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
    box_name = Box_arr[i,4]
    print(box_name)
    
    # - Obtain navlon and Navlat
    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
    list_imin.append(imin)
    list_imax.append(imax)
    list_jmin.append(jmin)
    list_jmax.append(jmax)
    list_name.append(box_name)
    list_latmin.append(y1)
    list_latmax.append(y2)
    list_lonmin.append(x1)
    list_lonmax.append(x2)
    
panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_MNA_1=pd.read_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t',index_col=0)
panda_box_MNA_2=panda_box_MNA_1.append(panda_box_MNA)
panda_box_MNA_2.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

for i in np.arange(200,int(a),1):
    
    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
    box_name = Box_arr[i,4]
    print(box_name)
    
    # - Obtain navlon and Navlat
    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
    list_imin.append(imin)
    list_imax.append(imax)
    list_jmin.append(jmin)
    list_jmax.append(jmax)
    list_name.append(box_name)
    list_latmin.append(y1)
    list_latmax.append(y2)
    list_lonmin.append(x1)
    list_lonmax.append(x2)

panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_MNA_2=pd.read_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t',index_col=0)
panda_box_MNA_3=panda_box_MNA_2.append(panda_box_MNA)
panda_box_MNA_3.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

400.0
Box_0
Box_1
Box_2
Box_3
Box_4
Box_5
Box_6
Box_7
Box_8
Box_9
Box_10
Box_11
Box_12
Box_13
Box_14
Box_15
Box_16
Box_17
Box_18
Box_19
Box_20
Box_21
Box_22
Box_23
Box_24
Box_25
Box_26
Box_27
Box_28
Box_29
Box_30
Box_31
Box_32
Box_33
Box_34
Box_35
Box_36
Box_37
Box_38
Box_39
Box_40
Box_41
Box_42
Box_43
Box_44
Box_45
Box_46
Box_47
Box_48
Box_49
Box_50
Box_51
Box_52
Box_53
Box_54
Box_55
Box_56
Box_57
Box_58
Box_59
Box_60
Box_61
Box_62
Box_63
Box_64
Box_65
Box_66
Box_67
Box_68
Box_69
Box_70
Box_71
Box_72
Box_73
Box_74
Box_75
Box_76
Box_77
Box_78
Box_79
Box_80
Box_81
Box_82
Box_83
Box_84
Box_85
Box_86
Box_87
Box_88
Box_89
Box_90
Box_91
Box_92
Box_93
Box_94
Box_95
Box_96
Box_97
Box_98
Box_99
Box_100
Box_101
Box_102
Box_103
Box_104
Box_105
Box_106
Box_107
Box_108
Box_109
Box_110
Box_111
Box_112
Box_113
Box_114
Box_115
Box_116
Box_117
Box_118
Box_119
Box_120
Box_121
Box_122
Box_123
Box_124
Box_125
Box_126
Box_127
Box_128
Box_129
Box_130
Box_131
Box_132
Box_133
Box_134
Box_135
Box_136
Box_137
Box_138
Box_139
Box_140
Box_141
Box_142
Box_143
Box_144
Box_145
Box_146
Box_147
Box_148
Box_149
Box_150
Box_151
Box_152
Box_153
Box_154
Box_155
Box_156
Box_157
Box_158
Box_159
Box_160
Box_161
Box_162
Box_163
Box_164
Box_165
Box_166
Box_167
Box_168
Box_169
Box_170
Box_171
Box_172
Box_173
Box_174
Box_175
Box_176
Box_177
Box_178
Box_179
Box_180
Box_181
Box_182
Box_183
Box_184
Box_185
Box_186
Box_187
Box_188
Box_189
Box_190
Box_191
Box_192
Box_193
Box_194
Box_195
Box_196
Box_197
Box_198
Box_199
Box_200
Box_201
Box_202
Box_203
Box_204
Box_205
Box_206
Box_207
Box_208
Box_209
Box_210
Box_211
Box_212
Box_213
Box_214
Box_215
Box_216
Box_217
Box_218
Box_219
Box_220
Box_221
Box_222
Box_223
Box_224
Box_225
Box_226
Box_227
Box_228
Box_229
Box_230
Box_231
Box_232
Box_233
Box_234
Box_235
Box_236
Box_237
Box_238

In [3]:
y1 = 41. 
y2 = 56.
x1 = -19.
x2 = -41.

navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA = read_datagrid_ORCA1(gridfile_ORCA1,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

# - Define box dimensions
a = (np.shape(navlon_ORCA)[0]-2.)*(np.shape(navlat_ORCA)[1]-2.)
Box_arr = np.empty((int(a),6),dtype=np.dtype('U100'))
print(a)

ii = 0
jj = 0
for i in np.arange(0,int(a),1):
    delta_lat1 = np.abs(navlat_ORCA[ii+1,jj] - navlat_ORCA[ii,jj])/2.
    delta_lat2 = np.abs(navlat_ORCA[ii+2,jj] - navlat_ORCA[ii+1,jj])/2.
    delta_lon1 = np.abs(navlon_ORCA[ii,jj+1] - navlon_ORCA[ii,jj])/2.
    delta_lon2 = np.abs(navlon_ORCA[ii,jj+2] - navlon_ORCA[ii,jj+1])/2.        
    Box_arr[i,:] = [str(navlat_ORCA[ii,jj]+delta_lat1),str(navlat_ORCA[ii+1,jj]+delta_lat2),str(navlon_ORCA[ii,jj]+delta_lon1),str(navlon_ORCA[ii,jj+1]+delta_lon2),'Box_'+str(i),str(i)]
    ii = ii + 1
    if ii >= int(np.shape(navlon_ORCA)[0])-2:
        ii = 0
        jj = jj + 1
        
name = Box_arr[:,4]

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

#i=0

#y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
#x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
#box_name = Box_arr[i,4]
#print(box_name)
    
# - Obtain navlon and Navlat
#navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
#list_imin.append(imin)
#list_imax.append(imax)
#list_jmin.append(jmin)
#list_jmax.append(jmax)
#list_name.append(box_name)
#list_latmin.append(y1)
#list_latmax.append(y2)
#list_lonmin.append(x1)
#list_lonmax.append(x2)

#panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
#panda_box_MNA.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

#list_imin = []
#list_imax = []
#list_jmin = []
#list_jmax = []
#list_name = []
#list_latmin = []
#list_latmax = []
#list_lonmin = []
#list_lonmax = []

#for i in np.arange(1,200,1):
    
#    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
#    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
#    box_name = Box_arr[i,4]
#    print(box_name)
    
    # - Obtain navlon and Navlat
#    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
#    list_imin.append(imin)
#    list_imax.append(imax)
#    list_jmin.append(jmin)
#    list_jmax.append(jmax)
#    list_name.append(box_name)
#    list_latmin.append(y1)
#    list_latmax.append(y2)
#    list_lonmin.append(x1)
#    list_lonmax.append(x2)
    
#panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
#panda_box_MNA_1=pd.read_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t',index_col=0)
#panda_box_MNA_2=panda_box_MNA_1.append(panda_box_MNA)
#panda_box_MNA_2.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

for i in np.arange(200,int(a),1):
    
    y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
    x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
    box_name = Box_arr[i,4]
    print(box_name)
    
    # - Obtain navlon and Navlat
    navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)
    
    list_imin.append(imin)
    list_imax.append(imax)
    list_jmin.append(jmin)
    list_jmax.append(jmax)
    list_name.append(box_name)
    list_latmin.append(y1)
    list_latmax.append(y2)
    list_lonmin.append(x1)
    list_lonmax.append(x2)

panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_MNA_2=pd.read_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t',index_col=0)
panda_box_MNA_3=panda_box_MNA_2.append(panda_box_MNA)
panda_box_MNA_3.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

400.0
Box_200
Box_201
Box_202
Box_203
Box_204
Box_205
Box_206
Box_207
Box_208
Box_209
Box_210
Box_211
Box_212
Box_213
Box_214
Box_215
Box_216
Box_217
Box_218
Box_219
Box_220
Box_221
Box_222
Box_223
Box_224
Box_225
Box_226
Box_227
Box_228
Box_229
Box_230
Box_231
Box_232
Box_233
Box_234
Box_235
Box_236
Box_237
Box_238
Box_239
Box_240
Box_241
Box_242
Box_243
Box_244
Box_245
Box_246
Box_247
Box_248
Box_249
Box_250
Box_251
Box_252
Box_253
Box_254
Box_255
Box_256
Box_257
Box_258
Box_259
Box_260
Box_261
Box_262
Box_263
Box_264
Box_265
Box_266
Box_267
Box_268
Box_269
Box_270
Box_271
Box_272
Box_273
Box_274
Box_275
Box_276
Box_277
Box_278
Box_279
Box_280
Box_281
Box_282
Box_283
Box_284
Box_285
Box_286
Box_287
Box_288
Box_289
Box_290
Box_291
Box_292
Box_293
Box_294
Box_295
Box_296
Box_297
Box_298
Box_299
Box_300
Box_301
Box_302
Box_303
Box_304
Box_305
Box_306
Box_307
Box_308
Box_309
Box_310
Box_311
Box_312
Box_313
Box_314
Box_315
Box_316
Box_317
Box_318
Box_319
Box_320
Box_321
Box_322
Box_323
Box_324
Box_325
Box_326
Box_327
Box_328
Box_329
Box_330
Box_331
Box_332
Box_333
Box_334
Box_335
Box_336
Box_337
Box_338
Box_339
Box_340
Box_341
Box_342
Box_343
Box_344
Box_345
Box_346
Box_347
Box_348
Box_349
Box_350
Box_351
Box_352
Box_353
Box_354
Box_355
Box_356
Box_357
Box_358
Box_359
Box_360
Box_361
Box_362
Box_363
Box_364
Box_365
Box_366
Box_367
Box_368
Box_369
Box_370
Box_371
Box_372
Box_373
Box_374
Box_375
Box_376
Box_377
Box_378
Box_379
Box_380
Box_381
Box_382
Box_383
Box_384
Box_385
Box_386
Box_387
Box_388
Box_389
Box_390
Box_391
Box_392
Box_393
Box_394
Box_395
Box_396
Box_397
Box_398
Box_399

In [3]:
y1 = 41. 
y2 = 56.
x1 = -19.
x2 = -41.

navlon_ORCA,navlat_ORCA,jmin_ORCA,jmax_ORCA,imin_ORCA,imax_ORCA = read_datagrid_ORCA1(gridfile_ORCA1,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)

# - Define box dimensions
a = (np.shape(navlon_ORCA)[0]-2.)*(np.shape(navlat_ORCA)[1]-2.)
Box_arr = np.empty((int(a),6),dtype=np.dtype('U100'))
print(a)

ii = 0
jj = 0
for i in np.arange(0,int(a),1):
    delta_lat1 = np.abs(navlat_ORCA[ii+1,jj] - navlat_ORCA[ii,jj])/2.
    delta_lat2 = np.abs(navlat_ORCA[ii+2,jj] - navlat_ORCA[ii+1,jj])/2.
    delta_lon1 = np.abs(navlon_ORCA[ii,jj+1] - navlon_ORCA[ii,jj])/2.
    delta_lon2 = np.abs(navlon_ORCA[ii,jj+2] - navlon_ORCA[ii,jj+1])/2.        
    Box_arr[i,:] = [str(navlat_ORCA[ii,jj]+delta_lat1),str(navlat_ORCA[ii+1,jj]+delta_lat2),str(navlon_ORCA[ii,jj]+delta_lon1),str(navlon_ORCA[ii,jj+1]+delta_lon2),'Box_'+str(i),str(i)]
    ii = ii + 1
    if ii >= int(np.shape(navlon_ORCA)[0])-2:
        ii = 0
        jj = jj + 1
        
name = Box_arr[:,4]

list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []

400.0

In [4]:
i=0
y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
box_name = Box_arr[i,4]
print(box_name)    
# - Obtain navlon and Navlat
navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)    
list_imin.append(imin)
list_imax.append(imax)
list_jmin.append(jmin)
list_jmax.append(jmax)
list_name.append(box_name)
list_latmin.append(y1)
list_latmax.append(y2)
list_lonmin.append(x1)
list_lonmax.append(x2)

Box_0

In [5]:
panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)
panda_box_MNA.to_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t')

In [6]:
i=1
list_imin = []
list_imax = []
list_jmin = []
list_jmax = []
list_name = []
list_latmin = []
list_latmax = []
list_lonmin = []
list_lonmax = []
y1 = float(Box_arr[i,0]); y2 = float(Box_arr[i,1]);
x2 = float(Box_arr[i,2]); x1 = float(Box_arr[i,3]);
box_name = Box_arr[i,4]
print(box_name)    
# - Obtain navlon and Navlat
navlon,navlat,jmin,jmax,imin,imax = read_datagrid(gridfile,latmin=y1,latmax=y2,lonmin=x2,lonmax=x1)    
list_imin.append(imin)
list_imax.append(imax)
list_jmin.append(jmin)
list_jmax.append(jmax)
list_name.append(box_name)
list_latmin.append(y1)
list_latmax.append(y2)
list_lonmin.append(x1)
list_lonmax.append(x2)

Box_1

In [7]:
panda_box_MNA=pd.DataFrame({'imin' : list_imin, 'imax' : list_imax,'jmin' : list_jmin, 'jmax' : list_jmax, 'latmin' : list_latmin, 'latmax' : list_latmax,'lonmin' : list_lonmin, 'lonmax' : list_lonmax},index = list_name)

In [8]:
panda_box_MNA_csv=pd.read_csv('boxes_MNA_1x1_eNATL60.csv',sep = '\t',index_col=0)
panda_box_MNA_bis=panda_box_MNA_csv+panda_box_MNA

In [11]:
panda_box_MNA_csv

       imin  imax  jmin  jmax     latmin     latmax     lonmin     lonmax
Box_0  3474  3534  2349  2409  41.451969  42.211447 -39.094934 -40.102634

In [12]:
panda_box_MNA

       imin  imax  jmin  jmax     latmin     latmax   lonmin     lonmax
Box_1  3474  3534  2409  2469  42.211447  42.963459 -39.1105 -40.119429

In [14]:
panda_box_MNA_csv.append(panda_box_MNA)

       imin  imax  jmin  jmax     latmin     latmax     lonmin     lonmax
Box_0  3474  3534  2349  2409  41.451969  42.211447 -39.094934 -40.102634
Box_1  3474  3534  2409  2469  42.211447  42.963459 -39.110500 -40.119429